var mongoose = require('mongoose');
var clientModel = require('./clientModel.js');

var caseSchema = new mongoose.Schema({
  name: {type: String, required: true},
  court: String,
  judge: String,
  causeNo: String,
  client: [{type: mongoose.Schema.Types.ObjectId, ref: "Client"}],
  caseDesc: String,
  joinAmendDate: Date,
  joinAmendDesc: String,
  witDiscDate: Date,
  witDiscDesc: String,
  expWitDiscDate: Date,
  expWitDiscDesc: String,
  discDate: Date,
  discDesc: String,
  plDiscDate: Date,
  plDiscDesc: String,
  defDiscDate: Date,
  defDiscDesc: String,
  motDate: Date,
  motDesc: String,
  discMotDate: Date,
  discMotDesc: String,
  dispMotDate: Date,
  dispMotDesc: String,
  nonDispMotDate: Date,
  nonDispMotDesc: String,
  motLimDate: Date,
  motLimDesc: String,
  mediationDate: Date,
  mediationDesc: String,
  mediatorSelecDate: Date,
  mediatorSelecDesc: String,
  pretConsDate: Date,
  pretConsDesc: String,
  pretExchangeDate: Date,
  pretExchangeDesc: String,
  finPretOrdDate: Date,
  finPretOrdDesc: String,
  trialBrfDate: Date,
  trialBrfDesc: String,
  jurInstDate: Date,
  jurInstDesc: String,
  witListDate: Date,
  witListDesc: String,
  exListDate: Date,
  exListDesc: String,
  depoDesigDate: Date,
  depoDesigDesc: String,
  trialBeginDate: Date,
  trialEndDate: Date,
  trialDesc:String
});

module.exports = mongoose.model('Case', caseSchema);
